import { FIELD_PALETTE } from "../field/field-palette";

export const HOUSE_PALETTE = {
  // Interior pigments extend the approved exterior, without introducing a new
  // time-of-day system. All furniture below is the 007 visual prototype.
  wall: "#e2d7bf",
  wallShade: "#cabfa8",
  trim: "#eadfc8",
  floor: "#9b7f5f",
  floorLight: "#a58967",
  floorShade: "#947759",
  floorRug: "#b6a789",
  rugBorder: "#777c63",
  wood: FIELD_PALETTE.wood,
  woodLight: "#b19165",
  woodDark: FIELD_PALETTE.woodDark,
  linen: "#8c9a7e",
  linenShade: "#647966",
  linenLight: "#e0d6bc",
  thread: "#c6ccb1",
  clay: "#b58064",
  ochre: "#bb9858",
  slate: "#657b81",
  ink: "#3e4e4a",
  canvas: "#747d62",
  cork: "#a88966",
  glass: FIELD_PALETTE.glass,
  glassSky: FIELD_PALETTE.sky,
  screen: "#293a3b",
  screenLight: "#485e60",
  paper: "#e5dcc4",
  paperEdge: "#c8bea5",
  metal: "#626b65",
  brass: "#ae9060",
  ceramic: "#e4d9bd",
  foliage: FIELD_PALETTE.foliage,
  foliageLight: FIELD_PALETTE.foliageLight,
  soil: FIELD_PALETTE.soil,
  sun: FIELD_PALETTE.sun,
  fill: FIELD_PALETTE.fill,
  bounce: "#958676",
  lamp: "#ffdda0",
  devMarker: FIELD_PALETTE.devMarker,
} as const;
